std='lua51'
exclude_files = {
    '**/Libs/**/*.lua',
    '.luacheckrc',
}

ignore = {
    '212/self',
    '631',
}

globals = {
    'LibStub',
    'Namespace',
    '_G',

    'BattlegroundCommanderDatabase',

    'C_ChatInfo',
    'C_ClassColor',
    'C_PvP',
    'C_UnitAuras',
    'CombatLogGetCurrentEventInfo',
    'CreateAtlasMarkup',
    'CreateColor',
    'CreateFrame',
    'DemoteAssistant',
    'DoReadyCheck',
    'Enum',
    'FlashClientIcon',
    'GetBattlefieldPortExpiration',
    'GetBattlefieldStatus',
    'GetCurrentRegion',
    'GetInstanceInfo',
    'GetInstanceInfo',
    'GetLFGRoleUpdate',
    'GetLocale',
    'GetMaxBattlefieldID',
    'GetNormalizedRealmName',
    'GetNumGroupMembers',
    'GetPlayerAuraBySpellID',
    'GetRealmName',
    'GetServerTime',
    'GetTime',
    'GetUnitName',
    'InCombatLockdown',
    'IsInGroup',
    'IsInRaid',
    'IsAltKeyDown',
    'IsControlKeyDown',
    'IsShiftKeyDown',
    'PlaySound',
    'PromoteToAssistant',
    'PromoteToLeader',
    'SendChatMessage',
    'SetRaidTarget',
    'Settings',
    'strsplit',
    'tinsert',
    'UISpecialFrames',
    'UnitClass',
    'UnitExists',
    'UnitFactionGroup',
    'UnitFullName',
    'UnitGUID',
    'UnitInOtherParty',
    'UnitIsConnected',
    'UnitIsGroupAssistant',
    'UnitIsGroupLeader',
    'UnitIsMercenary',
    'UnitIsPlayer',
    'UnitNameUnmodified',

    'DEBUFF_MAX_DISPLAY',
    'LE_PARTY_CATEGORY_HOME',
    'LE_PARTY_CATEGORY_INSTANCE',
    'SOUNDKIT',
    'UNKNOWNOBJECT',

    'date',
    'math',
    'pairs',
    'print',
    'select',
    'string',
    'table',
    'tonumber',
    'tostring',
    'type',
}
