name: Package and release
on:
    push:
        branches:
            - main
        tags:
            - '**'
jobs:
    release:
        runs-on: ubuntu-latest
        env:
            CF_API_KEY: ${{ secrets.CF_API_KEY }}
            WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
            GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
        steps:
            - name: Clone project
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Package and release
              uses: BigWigsMods/packager@v2
